### ISSUE TITLE
Jsonify the News

### ISSUE THREAD

**Issue by jnchin314** [Chiv2-Community/chivstats.xyz-web#14]
My initial thought here is to ultimately serve news and notes saved in a human writable/readable format in a file.  Yaml might be easy.

I would like to then read that file in and convert that to json output.  Need to figure out how django can do that.

Eitherway we can use the django json output eventually for the endpoint.

We can also use the json object to write out in the template if need be for the time being.

- Figure out a format to read/write.  Does yaml sound okay?  I can think of two fields for a NewsItem (content and date)
- Learn how to read files in python/django
- learn how to convert yaml to json.  Might be a django lib provided
- Unmarshalling json to python object to give to the current ui

**Comment by jnchin314** [comment]
this article is literally everything i want

https://python.land/data-processing/python-yaml

**Comment by jnchin314** [comment]
https://github.com/Chiv2-Community/chivstats.xyz-web/pull/16

**Comment by gimmic** [comment]
Resolved by #16
